# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AWKMT2_eigen <- function(t_idx, status0, status1, x0, x1, tau1, tau2, crange, test, type, nmethod) {
    .Call('AWKMT2cpp_AWKMT2_eigen', PACKAGE = 'AWKMT2cpp', t_idx, status0, status1, x0, x1, tau1, tau2, crange, test, type, nmethod)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('AWKMT2cpp_RcppExport_registerCCallable', PACKAGE = 'AWKMT2cpp')
})
